mariadb:
  server: 'localhost'
  port: '3306'
  user: '<user_name>'
  # Leave empty string for no password
  password: ''
  database-name: '<database_name>'
  table-prefix: 'pa_'

logging:
  # Logging when opening and closing connection with database
  log-connection: false
  # Logging jdbc version when opening connection with database
  log-jdbc: false
  # Logging driver name and version when opening connection with database
  log-driver: false
  # Logging creating and closing sessions for users
  log-sessions: false
  # Logging start and stop of recovery runnable
  log-recovery-runnable: false

recovery:
  # Recovery logging period in ticks
  # 1 second is 20 ticks
  period: 600